package com.aybee.steps;

import com.aybee.context.ScenarioContext;
import com.aybee.pages.ResetPasswordPage;
import com.aybee.utils.MailosaurHelper;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.testng.Assert;

public class ForgotPasswordFlowSteps {

    private final ScenarioContext context;

    // Remembers the last "new password" typed so we can write it back to the shared account
    // once the reset actually succeeds (this scenario reuses the shared account).
    private String lastNewPassword;

    // Instant just before Send Reset Link is clicked — the reset email must be received after this,
    // so we always fetch the NEW link and never a stale/already-used one from the reused mailbox.
    private long resetRequestedAtMillis;

    public ForgotPasswordFlowSteps(ScenarioContext context) {
        this.context = context;
    }

    // ─── FORGOT PASSWORD FORM ACTIONS ─────────────────────────────────────────────

    // Uses the email of the pre-created verified user stored in context.
    @When("I enter my registered email in the reset field")
    public void iEnterMyRegisteredEmailInResetField() {
        context.forgotPasswordPage.enterEmail(context.testUser.email);
    }

    // Accepts an arbitrary email string from the feature file (used for negative tests).
    @When("I enter {string} in the reset email field")
    public void iEnterEmailInResetField(String email) {
        context.forgotPasswordPage.enterEmail(email);
    }

    @When("I clear the password reset fields")
    public void iClearPasswordResetFields() {
        context.resetPasswordPage.clearPasswordFields();
    }

    @And("I click Send Reset Link")
    public void iClickSendResetLink() {
        // Capture the request instant (minus a small skew buffer) BEFORE clicking, so the email
        // fetch requires a link generated by THIS request — never an older, already-used one.
        resetRequestedAtMillis = System.currentTimeMillis() - 10_000;
        context.forgotPasswordPage.clickSendResetLink();
    }

    // ─── FORGOT PASSWORD ASSERTIONS ───────────────────────────────────────────────

    @Then("I should see a reset confirmation message")
    public void iShouldSeeResetConfirmation() {
        context.softAssert.assertTrue(context.forgotPasswordPage.isConfirmationVisible(),
                "Expected a reset confirmation message to appear after submitting the form");
    }

    @Then("I should not see a reset confirmation message")
    public void iShouldNotSeeResetConfirmation() {
        context.softAssert.assertFalse(context.forgotPasswordPage.isConfirmationVisible(),
                "Reset confirmation appeared for an unregistered email — platform must not send a reset link to unknown addresses");
    }

    @And("the Mailosaur inbox should receive a password reset email")
    public void mailosaurShouldReceiveResetEmail() {
        context.softAssert.assertNotNull(
                new MailosaurHelper().waitForEmailWithSubject(
                        context.testUser.email, "Forgot your password? Happens.", resetRequestedAtMillis),
                "Expected a password reset email in Mailosaur but none arrived");
    }

    // ─── RESET PASSWORD PAGE NAVIGATION ──────────────────────────────────────────

    // Extracts the reset URL from the Mailosaur email and navigates to it directly.
    @Given("I follow the password reset link from email")
    public void iFollowPasswordResetLinkFromEmail() {
        // Fetch the link generated by the latest Send Reset Link click (received after that instant),
        // so we never follow a stale/already-used reset URL from the reused mailbox.
        String resetUrl = new MailosaurHelper()
                .getResetPasswordUrlForEmail(context.testUser.email, resetRequestedAtMillis);
        com.aybee.driver.DriverManager.getDriver().get(resetUrl);
        context.resetPasswordPage = new ResetPasswordPage();
    }

    // ─── RESET PASSWORD FORM ACTIONS ──────────────────────────────────────────────

    @When("I enter {string} as the new password")
    public void iEnterAsNewPassword(String password) {
        lastNewPassword = password;
        context.resetPasswordPage.enterNewPassword(password);
    }

    @And("I enter {string} as the confirm password")
    public void iEnterAsConfirmPassword(String password) {
        context.resetPasswordPage.enterConfirmPassword(password);
    }

    @And("I save the new password")
    public void iSaveTheNewPassword() {
        context.resetPasswordPage.clickSave();
    }

    // ─── RESET PASSWORD ASSERTIONS ────────────────────────────────────────────────

    // No toast is shown — the platform redirects straight to the dashboard on success.
    @Then("I should see a password reset success notification")
    public void iShouldSeePasswordResetSuccess() {
        context.dashboardPage = new com.aybee.pages.DashboardPage();
        // Bubble processes the save and redirects to the dashboard on a delay — wait generously
        // (the default 15s visibility wait can expire before the redirect completes).
        boolean loaded = context.dashboardPage.isLoaded(30);
        context.softAssert.assertTrue(loaded,
                "Expected to be redirected to the dashboard after a successful password reset");
        // The shared account's password is now the value we just set — write it back so any
        // later scenario reusing this account signs in with the current password.
        if (loaded && context.testUser != null && lastNewPassword != null) {
            context.testUser.password = lastNewPassword;
        }
    }

    @Then("the save password button should be disabled")
    public void theSavePasswordButtonShouldBeDisabled() {
        Assert.assertFalse(context.resetPasswordPage.isSaveButtonEnabled(),
                "Expected the Save button to be disabled when password fields are not both filled");
    }
}
